version: "3.7"

services:
  # Postgres
  postgres:
    image: postgres
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: vkouk
      POSTGRES_URL: postgres://admin:vkouk@postgres:5432/trucker
      POSTGRES_DB: trucker
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always

  # Backend API
  truck-api:
    container_name: backend
    build: ./
    command: npm run dev
    working_dir: /usr/src/truck-app
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/truck-app
